In [1]:
# 마찬가지로 Java나 다른 언어의 중괄호 표기를 ':' 이 대체하고 있다.
class PyTestClass:
    """It's for Test Class"""
    pass

# dir() 사용할 수 있는 모듈(라이브러리)을 보여준다.
print(dir())
# type은 당연히 class
print(type(PyTestClass))

['In', 'Out', 'PyTestClass', '_', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_ih', '_ii', '_iii', '_oh', 'exit', 'get_ipython', 'quit']
<class 'type'>


In [2]:
# 자바에서는 매서드만 따로 빠져있는 경우가 없었음
# 외부에 def A()만 딸랑 있는 경우
# 동일하게 매서드라고 생각하면 된다.
# 매서드는 호출해야 하듯이 마찬가지로 호출을 해줘야 동작이 된다.
# def plus(a, b):
#     return a + b

class Person:
    Name = "Default Name"
    
    # public void Print(void):
    #    self == this -> True
    def Print(self):
        print("My name is {0}".format(self.Name))

# Person p1 = new Person()
p1 = Person()
p1.Print()
print('#####################')

# 현재는 전부 public이므로 외부에서 마음대로 참조 및 변경이 가능
p1.Name = "My name is Python3"
p1.Print()
# 직접 클래스에 있는 Print를 호출한다는 방식으로도 사용이 가능하다.
# 이것은 순수한 인터프리터 언어라 가능한 것임
Person.Print(p1)

My name is Default Name
#####################
My name is My name is Python3
My name is My name is Python3


In [3]:
class Person:
    Name = "Default Name"

    def Print(self):
        print("My name is {0}".format(self.Name))
        
p1 = Person()
p1.Name = "Python3"

p2 = Person()

# 클래스 구조는 같아도 객체가 서로 다르므로
# 내부에 설정하는 값은 다르다.
print("p1.name =", p1.Name)
print("p2.name =", p2.Name)

p1.name = Python3
p2.name = Default Name


In [5]:
# 클래스 내부 변수를 
# 아래와 같이 언제든지 마음대로 추가할 수 있다.
Person.title = "Python3 Test"
print("p1.title =", p1.title)
print("p2.title =", p2.title)
print("Person.title =", Person.title)

p1.age = 20
print("p1.age =", p1.age)

p1.title = Python3 Test
p2.title = Python3 Test
Person.title = Python3 Test
p1.age = 20


In [9]:
# str1이 전역으로 생성되어 있음
str1 = "Not Class Member"

class NonSelfTest:
    str1 = ""
    
    def Set(self, msg):
        self.str1 = msg
        
    def Print(self):
        print(self.str1)
        print(str1)

# 객체를 생성        
test = NonSelfTest()
# Setter를 활용해서 "Test Message"를 설정
test.Set("Test Message")
# 결과를 출력해서 "Test Message"를 보고 싶었으나
# 출력된 것은 전역 변수인 "Not Class Member"가 출력됨
# self를 명시하지 않고 이름이 같은게 있다면 전역변수에 접근하게 된다.
test.Print()

Test Message
Not Class Member


In [11]:
class ClassTest:
    data = "Default"
    
ct1 = ClassTest()
ct2 = ClassTest()

print(ct1.data)
print(ct2.data)

# __class__.data로 지정하면
# 해당 객체의 클래스 타입을 파악하여
# 해당 클래스에 대한 모든 객체의 값을 변경한다.
ct1.__class__.data = "Change"
print('###################')
print(ct1.data)
print(ct2.data)

# __class__가 없으면 대상 객체만 변경된다.
ct2.data = "Only this"
print('###################')
print(ct1.data)
print(ct2.data)

Default
Default
###################
Change
Change
###################
Change
Only this


In [14]:
# 조급할 필요 없음
# 어차피 전세계의 모든 사람은 수학을 싫어한다.
# 이과 나와도 똑같다.
# 누가 오래 비비냐 승부
# 실제 적분은 limit dx -> 0 
dx = 0.00001

def integralRange(start, end):
    loopNum = (int)((end - start) / dx + 1)
    area = 0
    # 0 ~ loopNum - 2
    for i in range(loopNum - 1):
        curX = dx * i               # current X
        area += dx * (curX ** 2)
        
    return area;

area = integralRange(0, 3)
print("x^2의 0 ~ 3까지 정적분 결과 =", area)

x^2의 0 ~ 3까지 정적분 결과 = 8.999955000049939


In [16]:
class Vehicle:
    pass

class Fish:
    pass

# 파이썬에서 상속은 아래와 같이 한다.
# Airplane(Vehicle) <<< Airplane은 Vehicle을 상속 받았음을 의미한다.
class Airplane(Vehicle):
    pass

v, a = Vehicle(), Airplane()

# 자식은 부모에 대한 인스턴스가 될 수 있다.
print("v is Instance of Vehicle:", isinstance(v, Vehicle))
print("a is IoV:", isinstance(a, Vehicle))
print("v is Instance of Airplane:", isinstance(v, Airplane))
print("v is Instance of Object:", isinstance(v, object))
print("v is Instance of Fish:", isinstance(v, Fish))
print("int is Instance of Object:", isinstance(int, object))

v is Instance of Vehicle: True
a is IoV: True
v is Instance of Airplane: False
v is Instance of Object: True
v is Instance of Fish: False
int is Instance of Object: True


In [18]:
class Vehicles:
    # __init__ 이 키워드가 붙어있으면 Constructor(생성자)
    # init: 초기화
    def __init__(self, value):
        self.Value = value
        print("Vehicles Class Constructor! Value =", value)
        
    # __del__ 이 키워드가 붙으면 Destructor(소멸자)
    def __del__(self):
        print("Vehicles Class Destructor!")
        
def test():
    # t라는 객체는 test 함수 내에서만 살아있는 지역변수(Stack)
    t = Vehicles(333)
    # 그러므로 test 함수가 끝나면 소멸자가 호출된다.
    print("정말?")
    
test()
print("레알?")

Vehicles Class Constructor! Value = 333
정말?
Vehicles Class Destructor!
레알?


In [40]:
class CntManager:
    cnt = 0

    def __init__(self):
        CntManager.cnt += 1
        
    # self를 사용하지 않고 클래스 자체의 cnt로 접근하라고 하고 있음
    def staticPrintCnt():
        print("Instance cnt:", CntManager.cnt)
        
    # staticmethod - 언제든지 외부에서
    # 쉽게 참조하여 호출할 수 있게 만들어줌
    # 즉 클래스에 있는 staticPrintCnt 매서드를
    # 조금 더 이름이 단순한 sPrintCnt로 대체
    # 별칭
    sPrintCnt = staticmethod(staticPrintCnt)
        
    # 결국 classmethod로 만든 classPrintCnt의 cls는
    # self 와 동일한 역할을 수행하게 된다.
    def classPrintCnt(cls):
        print("Instance cnt:", cls.cnt)
        
    # classmethod - 디폴트로 첫 번째 인자가 자신의 클래스 셋팅됨
    # 별칭
    cPrintCnt = classmethod(classPrintCnt)
    
# 결국 생성자를 통해
# 모든 CntManager 기반의 객체들의 cnt 값을 증가시킴
a, b, c = CntManager(), CntManager(), CntManager()

CntManager.sPrintCnt()
b.sPrintCnt()

# 파라미터(인자) 표기가 없어도 알아서 디폴트로 클래스 자신이 셋팅됨
CntManager.classPrintCnt()
c.classPrintCnt()

Instance cnt: 3
Instance cnt: 3


TypeError: classPrintCnt() missing 1 required positional argument: 'cls'

In [32]:
# 자식이 부모 클래스를 상속 받을때 생성자를 어떻게 처리해야 하는가 ?
class Person:
    # Person의 생성자
    def __init__(self, name, phoneNum):
        self.name = name
        self.phoneNum = phoneNum
        
    #def printInfo(self):
    #    print("Info(name: {0}, Phone Num: {1})".format(self.name, self.phoneNum))
        
    #def printPersonData(self):
    #    print("Person(name: {0}, Phone Num: {1})".format(self.name, self.phoneNum))
        
class Student(Person):
    # Student의 생성자
    # 자바와는 다르게 생성자 내부에서
    # 부모 클래스에 대한 부분을 처리해줘야 한다.
    def __init__(self, name, phoneNum, subject, studentId):
        self.name = name
        self.phoneNum = phoneNum
        self.subject = subject
        self.studentId = studentId
        
p = Person("Maron", "045-667-1853")
s = Student("Lunar", "406-708-3821", "Electronic Engineering", "7383492")

# 생성된 객체를 __dict__ 통해서 살펴보면
# 내부의 정보들을 획득할 수 있다.
print(p.__dict__)
print(s.__dict__)

{'name': 'Maron', 'phoneNum': '045-667-1853'}
{'name': 'Lunar', 'phoneNum': '406-708-3821', 'subject': 'Electronic Engineering', 'studentId': '7383492'}


In [33]:
print(p)

In [37]:
import math

class Circle(object):
    def __init__(self, r):
        self.r = r
        
    def setter(self, r):
        self.r = r
        
    # pi * r^2 (원의 넓이)
    @property
    def area(self):
        return math.pi * self.r ** 2
    
    # 2 * pi * r (원의 둘레)
    @property
    def circumference(self):
        return 2 * math.pi * self.r
    
c = Circle(3.0)
print(c.area)
print(c.circumference)

c.setter(7.0)
print(c.area)
print(c.circumference)

28.274333882308138
18.84955592153876
153.93804002589985
43.982297150257104


In [45]:
class DummyClass:
    def __init__(self):
        self.var1 = 3
        self._var2 = 'Python'
        self.__var3 = 'Class'
        
dp = DummyClass()

# 노 언더바 - public
print(dp.var1)
# 언더바 1개 - protected
print(dp._var2)
# 언더바 2개 - private
#print(dp.__var3)
print(dp._DummyClass__var3)

3
Python
Class


In [48]:
class Animal:
    def __init__(self, name, height, weight):
        self.name = name
        self.height = height
        self.weight = weight
        
    def info(self):
        print("name:", str(self.name))
        print("height:", str(self.height))
        print("weight:", str(self.weight))
        
class Carnivore(Animal):
    def __init__(self, name, height, weight, feed, sound):
        # Animal에 있는 생성자를 호출해줘 ~
        # 하고 강제 요청을 한 것
        # super와 동일하다.
        Animal.__init__(self, name, height, weight)
        self.feed = feed
        self.sound = sound
        
    def sounds(self):
        print(str(self.name) + ": " + str(self.sound))
        
wolf = Carnivore("Timber Wolf", 140, 75, "Meat", "Howl")

print(wolf.__dict__)
wolf.sounds()

{'name': 'Timber Wolf', 'height': 140, 'weight': 75, 'feed': 'Meat', 'sound': 'Howl'}
Timber Wolf: Howl


In [49]:
class Parent(object):
    def __init__(self, num):
        self.num = num
        
    def printMsg(self):
        print("I'm Super Class")
        
class Child(Parent):
    def __init__(self, num):
        # super(Child, self) 라는 것이
        # Child의 super Class를 불러오라는 의미
        # Super Class를 불러와서 그것의 __init__ 이므로
        # 결국 Super Class의 생성자를 호출하는것과 같다.
        super(Child, self).__init__(num)
        
    def printMsg(self):
        print("I'm a Sub Class: [%s]" % str(self.num))
        super(Child, self).printMsg()
        
c = Child(3)
c.printMsg()

I'm a Sub Class: [3]
I'm Super Class


In [56]:
class OpOverloadEx(object):
    def __init__(self, num):
        print("__init__ is called")
        self.num = num
        
    # 파이썬에서 Java의 toString 역할을 해준다.
    def __repr__(self):
        print("__repr__ is called")
        return str(self.num)
    
    # 덧셈에 대한 연산자 오버로딩
    # obj1 + obj2 == obj1.__add__(obj2) -> True
    def __add__(self, other):
        print("__add__ is called")
        return OpOverloadEx(self.num + other.getNum())
    
    # 뺄셈에 대한 연산자 오버로딩
    def __sub__(self, other):
        print("__sub__ is called")
        return OpOverloadEx(self.num - other.getNum())
    
    def getNum(self):
        return self.num
    
obj1 = OpOverloadEx(10)
obj2 = OpOverloadEx(22)

# Java에서 toString 같은것이 지정이 안되어 있으면
# 여기서는 실제 obj1, obj2 객체의 주소값이 나왔었다.
#print(obj1)   # 10
#print(obj2)   # 22

# 
print(obj1 + obj2)
print(obj1 - obj2)

__init__ is called
__init__ is called
__add__ is called
__init__ is called
__repr__ is called
32
__sub__ is called
__init__ is called
__repr__ is called
-12


In [100]:
class CustomComplex(complex):
    def __lt__(self, other):
        print("__lt__ self =", self)
        print("__lt__ other =", other)
        return self < other
    
class Complex(object):
    # 생성자
    def __init__(self, real, imag):
        self.real = real
        self.imag = imag
    
    # toString
    def __repr__(self):
        print("__repr__ self.imag =", self.imag)
        #print((CustomComplex)(self.imag) < 0j)
        #if((CustomComplex)(self.imag) < 0j):
        #    return str(self.real) + " - " + str(abs(self.imag))
        #else:
        #    return str(self.real) + " + " + str(self.imag)
        return str(self.real) + " + " + str(self.imag)
    
    # 덧셈 연산자 오버로딩
    def __add__(self, other):
        return Complex(self.real + other.real, self.imag + other.imag)
    
    # 뺄셈 연산자 오버로딩
    def __sub__(self, other):
        return Complex(self.real - other.real, self.imag - other.imag)

z1 = Complex(3, 2j)
z2 = Complex(2, 4j)

#print(z1)
#print(z2)

print(z1 + z2)
print(z1 - z2)

__repr__ self.imag = 6j
5 + 6j
__repr__ self.imag = -2j
1 + -2j


In [102]:
import numpy as np

x = 1.0
y = np.sin(x)

print(y)

0.8414709848078965


In [103]:
import math

print(math.pi / 180.0)

0.017453292519943295


In [107]:
import numpy
import math

x = 1.0

print(numpy.sin(x))
print(math.sin(x))

0.8414709848078965
0.8414709848078965


In [108]:
# import numpy  ->      numpy 라이브러리를 사용하겠다.
# import numpy as np -> numpy 라이브러리를 np라는 이름으로 사용하겠다.
import numpy as np

vec = np.array([0, 1, 2, 3, 4])
length = len(vec)

print(vec)
print(length)

[0 1 2 3 4]
5


In [109]:
import numpy as np

A = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(A)
print(A.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [111]:
import numpy as np

series1 = np.arange(5)
series2 = np.arange(0, 10, 3)

print(series1)
print(series2)

print(type(series1))
print(type(series2))

[0 1 2 3 4]
[0 3 6 9]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [113]:
import numpy as np

one = np.ones((3, 3))
zero = np.zeros((3, 3))

print(one)
print(zero)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [115]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])

print(A + B)
print(A - B)

[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]


In [116]:
import numpy as np

# 이 배열은 수치해석용 배열
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(A[0])
print(A[-1])
print(A[3])

1
8
4


In [117]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(A[0])
print(A[1])
print(A[-1])

[1 2 3]
[4 5 6]
[7 8 9]


In [118]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(A[:, 0])   # 첫 번째 열
print(A[:, 1])   # 두 번째 열
print(A[:, -1])  # 마지막 열

[1 4 7]
[2 5 8]
[3 6 9]


In [133]:
import numpy as np

# 검산을 하고 싶다면 값을 크게 만들도록 한다(대신 정밀도가 떨어짐)
# 정밀도는 값을 작게 만들수록 커진다.
dx = 0.01

def integralRange(start, end):
    # np.arange()를 통해서 start 부터 end 사이에
    # dx 로 몇 개가 만들어지는지 자동으로 계산을 해준다.
    # curX(계산할 지점의 x 값 자체를 배열로 만들어줌)
    curX = np.arange(start, end, dx)
    #print(curX)
    #print("\n")
    # 모든 y^2
    Y = curX ** 2
    #print(Y)
    #print("\n")
    # 모든 사각형의 넓이값들
    eachBlock = dx * Y
    #print(eachBlock)
    #print("\n")
    # eachBlock(모든 사각형의 넓이값들)을 모두 합산해라!
    area = np.sum(eachBlock)
    #print(area)
    return area

area = integralRange(0, 3)
print("x^2의 0 ~ 3까지 정적분 결과 =", area)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.   1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.1  1.11
 1.12 1.13 1.14 1.15 1.16 1.17 1.18 1.19 1.2  1.21 1.22 1.23 1.24 1.25
 1.26 1.27 1.28 1.29 1.3  1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39
 1.4  1.41 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.5  1.51 1.52 1.53
 1.54 1.55 1.56 1.57 1.58 1.59 1.6  1.61 1.62 1.63 1.64 1.65 1.66 1.67
 1.68 1.69 1.7  1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.8  1.81
 1.82 1.83 1.84 1.85 1.86 1.87 1.88 1.89 1.9  1.91 1.92 1.93 1.94 1.95
 1.96 

In [127]:
curX = np.arange(0, 5, 1)
print(curX)
Y = curX ** 2
print(Y)
eachBlock = curX * Y
print(eachBlock)

[0 1 2 3 4]
[ 0  1  4  9 16]
[ 0  1  8 27 64]
